apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: employee-serving
  annotations:
    scenarios.ai.sap.com/description: "Employee Suitability API"
    scenarios.ai.sap.com/name: "Employee Suitability"
    executables.ai.sap.com/description: "Serve employee model"
    executables.ai.sap.com/name: "serving"
    artifacts.ai.sap.com/trainedmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "employee-suitability"
    ai.sap.com/version: "1.0"
    ai.sap.com/resourcePlan: starter
spec:
  inputs:
    artifacts:
      - name: trainedmodel
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      labels: |
        ai.sap.com/resourcePlan: starter
      annotations: |
        autoscaling.knative.dev/metric: cpu
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/targetBurstCapacity: "0"
    spec: |
      predictor:
        imagePullSecrets:
          - name: credstutorialrepo
        containers:
          - name: kserve-container
            image: docker.io/tarun0305/employee-suitability:01
            command: ["/bin/sh", "-c"]
            args:
              - "python /app/src/serve.py"
            ports:
              - containerPort: 9001
                protocol: TCP
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.trainedmodel}}"
